#!/usr/bin/env node
/**
 * generate_index.js
 * Rebuilds src/domains/*.js question bank files from problems/ folder problem.json files.
 * Run this after adding or editing any problem.json.
 *
 * Usage:
 *   node scripts/generate_index.js
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve } from 'path';

const PROBLEMS_DIR = resolve('problems');
const SRC_DOMAINS_DIR = resolve('src/domains');

const DOMAIN_FILE_MAP = {
  'rtl-design': 'rtlDesign.js',
  'computer-architecture': 'computerArchitecture.js',
  'design-verification': 'designVerification.js',
  'programming': 'programming.js',
};

function findAllProblemJsons(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      results.push(...findAllProblemJsons(fullPath));
    } else if (entry === 'problem.json') {
      results.push(fullPath);
    }
  }
  return results;
}

// Group problem.json files by domain
const byDomain = {};
for (const domain of Object.keys(DOMAIN_FILE_MAP)) {
  byDomain[domain] = {};
}

const allFiles = findAllProblemJsons(PROBLEMS_DIR);

for (const filePath of allFiles) {
  let data;
  try {
    data = JSON.parse(readFileSync(filePath, 'utf8'));
  } catch (e) {
    console.warn(`⚠️  Skipping ${filePath}: parse error — ${e.message}`);
    continue;
  }

  const { domain, category } = data;
  if (!domain || !byDomain[domain]) continue; // rtl-debug handled separately

  if (!byDomain[domain][category]) {
    byDomain[domain][category] = [];
  }
  byDomain[domain][category].push(data);
}

// Write each domain file
for (const [domain, categories] of Object.entries(byDomain)) {
  const outFile = join(SRC_DOMAINS_DIR, DOMAIN_FILE_MAP[domain]);
  const varName = DOMAIN_FILE_MAP[domain].replace('.js', '');

  const lines = [
    `/**`,
    ` * ${domain} — auto-generated by scripts/generate_index.js`,
    ` * Do not edit directly. Edit the problem.json files under problems/${domain}/ instead.`,
    ` */`,
    ``,
    `const ${varName} = {`,
  ];

  for (const [category, problems] of Object.entries(categories)) {
    lines.push(`  ${JSON.stringify(category)}: [`);
    for (const p of problems) {
      lines.push(`    ${JSON.stringify(p, null, 2).split('\n').join('\n    ')},`);
    }
    lines.push(`  ],`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`export default ${varName};`);
  lines.push(``);

  writeFileSync(outFile, lines.join('\n'), 'utf8');
  const count = Object.values(categories).reduce((s, arr) => s + arr.length, 0);
  console.log(`✅ Wrote ${outFile}  (${count} problems)`);
}

console.log('\nDone. Run `node scripts/validate_problem.js --all` to check for errors.');
